-- Migration 008: Add RAG support for meeting transcripts
-- Enable pgvector extension for vector embeddings
-- Create tables for chunks, chat sessions, and chat messages

-- Enable pgvector extension
CREATE EXTENSION IF NOT EXISTS vector;

-- Store chunked meeting content with embeddings
CREATE TABLE IF NOT EXISTS meeting_chunks (
    id SERIAL PRIMARY KEY,
    meeting_id VARCHAR(50) NOT NULL REFERENCES meetings(id) ON DELETE CASCADE,
    language VARCHAR(10) NOT NULL,
    chunk_index INTEGER NOT NULL,
    chunk_text TEXT NOT NULL,

    -- Speaker metadata for context
    speaker_id VARCHAR(50),
    speaker_name VARCHAR(255),

    -- Temporal metadata
    start_timestamp TIMESTAMP,
    end_timestamp TIMESTAMP,
    start_offset_seconds FLOAT,
    end_offset_seconds FLOAT,

    -- Embedding vector (384 dimensions for all-MiniLM-L6-v2)
    embedding vector(384),

    -- Processing metadata
    processing_status VARCHAR(20) DEFAULT 'pending', -- pending, processing, completed, failed
    created_at TIMESTAMP DEFAULT NOW(),

    UNIQUE(meeting_id, language, chunk_index)
);

-- Chat sessions for RAG conversations
CREATE TABLE IF NOT EXISTS meeting_chat_sessions (
    id SERIAL PRIMARY KEY,
    session_id VARCHAR(50) UNIQUE NOT NULL,
    meeting_id VARCHAR(50) NOT NULL REFERENCES meetings(id) ON DELETE CASCADE,
    language VARCHAR(10) NOT NULL,
    user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    last_activity TIMESTAMP DEFAULT NOW()
);

-- Chat messages history
CREATE TABLE IF NOT EXISTS meeting_chat_messages (
    id SERIAL PRIMARY KEY,
    session_id VARCHAR(50) NOT NULL REFERENCES meeting_chat_sessions(session_id) ON DELETE CASCADE,
    role VARCHAR(20) NOT NULL, -- 'user' or 'assistant'
    content TEXT NOT NULL,

    -- Context chunks used for this response (array of chunk IDs)
    context_chunk_ids INTEGER[],

    created_at TIMESTAMP DEFAULT NOW()
);

-- Indexes for performance optimization
CREATE INDEX IF NOT EXISTS idx_chunks_meeting_lang ON meeting_chunks(meeting_id, language);
CREATE INDEX IF NOT EXISTS idx_chunks_status ON meeting_chunks(meeting_id, processing_status);

-- Vector similarity search index (IVFFlat with 100 lists for ~1k-100k vectors)
CREATE INDEX IF NOT EXISTS idx_chunks_embedding ON meeting_chunks
    USING ivfflat (embedding vector_cosine_ops)
    WITH (lists = 100);

-- Chat session indexes
CREATE INDEX IF NOT EXISTS idx_chat_sessions_meeting ON meeting_chat_sessions(meeting_id);
CREATE INDEX IF NOT EXISTS idx_chat_messages_session ON meeting_chat_messages(session_id, created_at);

-- Comments for documentation
COMMENT ON TABLE meeting_chunks IS 'Chunked meeting transcripts with vector embeddings for RAG retrieval';
COMMENT ON COLUMN meeting_chunks.embedding IS 'Vector embedding (384 dims) generated by sentence-transformers/all-MiniLM-L6-v2';
COMMENT ON COLUMN meeting_chunks.processing_status IS 'Status: pending (waiting), processing (in progress), completed (success), failed (error)';
COMMENT ON TABLE meeting_chat_sessions IS 'RAG chat sessions for querying meeting transcripts';
COMMENT ON TABLE meeting_chat_messages IS 'Chat message history for RAG conversations';
